spring:
  application:
    name: university-pet-project-website
  datasource:
    url: jdbc:postgresql://localhost:5432/website-user-registry
    username: postgres
    password: 1
  config:
    import: google-credentials.properties
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${clientId}
            clientSecret: ${clientSecret}
            redirectUri: ${redirectUri}
            scope: ${scope}
  flyway:
    locations: classpath:db/migration
    enabled: true
    clean-disabled: true
    baseline-on-migrate: true
    schemas: public
    default-schema: public
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/website-user-registry
    user: postgres
    password: 1

server:
  port: 8000

logging:
  level:
    root: info
    dmytro: debug